CadastroDeFornecedores/Models/ErrorViewModel.cs
namespace CadastroDeFornecedores.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadastroDeFornecedores/Models/FornecedorModel.cs
using System.ComponentModel.DataAnnotations;

namespace CadastroDeFornecedores.Models
{
    public class FornecedorModel
    {
        [Key]
        public int Id { get; set; }
        public string CNPJ { get; set; }
        public string? RazaoSocial { get; set; }
        public string? NomeFantasia { get; set; }
        public string Email { get; set; }
        public string? Telefone { get; set; }
        public string NomePessoaContato { get; set; }
        public string? logradouro {  get; set; }
        public string? Numero { get; set; }
        public string? Complemento { get; set; }
        public string? Bairro { get; set; }
        public string? Estado { get; set; }
        public string? Municipio { get; set; }
        public string? CEP { get; set; }
    }
}

CadastroDeFornecedores/Controllers/FornecedorController.cs
using CadastroDeFornecedores.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
//using CadastroDeFornecedores.Data;
using CadastroDeFornecedores.Models;

namespace CadastroDeFornecedores.Controllers
{
    public class FornecedorController : Controller
    {
        private readonly AppCont _appCont;
        public FornecedorController(AppCont appCont)
        {
            _appCont = appCont;
        }

        public IActionResult Index()
        {
            var allTasks = _appCont.Fornecedor.ToList();
            return View(allTasks);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedor = await _appCont.Fornecedor.FirstOrDefaultAsync(mbox => mbox.Id == id);
            if (fornecedor == null)
            {
                return NotFound();
            }

            return View(fornecedor);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(FornecedorModel fornecedor)
        {
            if (ModelState.IsValid)
            {
                _appCont.Add(fornecedor);
                await _appCont.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fornecedor);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedor = await _appCont.Fornecedor.FindAsync(id);
            if (fornecedor == null)
            {
                return NotFound();
            }
            return View(fornecedor);
        }

        private bool fornecedorExists(int id)
        {
            return _appCont.Fornecedor.Any(e => e.Id == id);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, FornecedorModel fornecedor)
        {
            if (id != fornecedor.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _appCont.Update(fornecedor);
                    await _appCont.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!fornecedorExists(fornecedor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fornecedor);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedor = await _appCont.Fornecedor.FirstOrDefaultAsync(m => m.Id == id);
            if (fornecedor == null)
            {
                return NotFound();
            }
            return View(fornecedor);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var fornecedor = await _appCont.Fornecedor.FindAsync(id);
            _appCont.Fornecedor.Remove(fornecedor);
            await _appCont.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

CadastroDeFornecedores/Controllers/HomeController.cs
using CadastroDeFornecedores.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CadastroDeFornecedores.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadastroDeFornecedores/Views/Fornecedor/Create.cshtml
@model CadastroDeFornecedores.Models.FornecedorModel

@{
    ViewData["Title"] = "Criar fornecedor";
}

<h1>Adicionar Fornecedor</h1>

<h4>Fornecedor</h4>
<hr/>
<div class="row">
    <div @* class="col-md-6" *@>
        <form class="row g-3" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-md-4">
                <label asp-for="CNPJ" class="form-label">CNPJ</label>
                <div class="input-group">
                    <!-- Adicione uma div com a classe "input-group" -->
                    <input asp-for="CNPJ" type="text" class="form-control" id="cleave-cnpj" />
                    <button class="btn btn-primary" id="search">Consultar CNPJ</button> <!-- Use a classe "btn" para estilizar o botão -->
                </div>
                <span asp-validation-for="CNPJ" class="text-danger"></span>
            </div>

            
            <div >
                <label asp-for="RazaoSocial" class="form-label">Razao Social</label>
                <input asp-for="RazaoSocial" class="form-control" id="razaoSocial" />
                <span asp-validation-for="RazaoSocial" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="NomeFantasia" class="form-label">Nome Fantasia</label>
                <input asp-for="NomeFantasia" class="form-control" id="nomeFantasia" />
                <span asp-validation-for="NomeFantasia" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="Email" class="form-label">Email</label>
                <input asp-for="Email" class="form-control" id="email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="Telefone" class="form-label">Telefone</label>
                <input asp-for="Telefone" class="form-control" id="telefone" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>

            <div class="col-md-6">
                <label asp-for="NomePessoaContato" class="form-label">Nome</label>
                <input asp-for="NomePessoaContato" class="form-control" />
                <span asp-validation-for="NomePessoaContato" class="text-danger"></span>
            </div>

            <div class="col-md-8">
                <label asp-for="CEP" class="form-label">CEP</label>
                <input asp-for="CEP" class="form-control" id="cep"/>
                <span asp-validation-for="CEP" class="text-danger"></span>
            </div>



            <div class="col-md-8">
                <label asp-for="logradouro" class="form-label">logradouro</label>
                <input asp-for="logradouro" class="form-control" id="logradouro" />
                <span asp-validation-for="logradouro" class="text-danger"></span>
            </div>



            <div class="col-md-5">
                <label asp-for="Complemento" class="form-label">Complemento</label>
                <input asp-for="Complemento" class="form-control" id="complemento"/>
                <span asp-validation-for="Complemento" class="text-danger"></span>
            </div>



            <div class="col-md-1">
                <label asp-for="Numero" class="form-label">Numero</label>
                <input asp-for="Numero" class="form-control" id="numero"/>
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>


            <div class="col-md-6">
                <label asp-for="Bairro" class="form-label">Bairro</label>
                <input asp-for="Bairro" class="form-control" id="bairro"/>
                <span asp-validation-for="Bairro" class="text-danger"></span>
            </div>


            <div class="col-md-4">
                <label asp-for="Municipio" class="form-label">Municipio</label>
                <input asp-for="Municipio" class="form-control" id="municipio"/>
                <span asp-validation-for="Municipio" class="text-danger"></span>
            </div>


            <div class="col-md-4">
                <label asp-for="Estado" class="form-label">Estado</label>
                <input asp-for="Estado" class="form-control" id="Estado" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>



            <div class="form-group" style="padding-top:10px">
                <input type="submit" value="Inserir" class="btn btn-primary btn-sm"/>
                <a class="btn btn-secondary text-white btn-sm" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

CadastroDeFornecedores/Views/Fornecedor/Delete.cshtml
@model CadastroDeFornecedores.Models.FornecedorModel

@{
    ViewData["Title"] = "Apagar Fornecedor";
}

<h1>Apagar Fornecedor</h1>

<h3>Você tem certeza que deseja apagar este fornecedor?</h3>
<div>
    <h4>Fornecedor</h4>
    <hr />

    <dl class="row">



        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.RazaoSocial) *@
            Razao Social
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RazaoSocial)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.NomeFantasia) *@
            Nome Fantasia
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomeFantasia)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.NomeFantasia) *@
            CNPJ
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CNPJ)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Email) *@
            Email
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Telefone) *@
            Telefone
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.NomePessoaContato) *@
            Nome
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomePessoaContato)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.CEP) *@
            CEP
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CEP)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.logradouro) *@
            logradouro
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.logradouro)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Complemento) *@
            Complemento
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Complemento)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Numero) *@
            Numero
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Numero)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Bairro) *@
            Bairro
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bairro)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Municipio) *@
            Municipio
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Municipio)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Municipio) *@
            Estado
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>




    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger btn-sm" />
        <a class="btn btn-secondary text-white btn-sm" asp-action="Index">Voltar</a>
    </form>

</div>

CadastroDeFornecedores/Views/Fornecedor/Details.cshtml
@model CadastroDeFornecedores.Models.FornecedorModel

@{
    ViewData["Title"] = "Detalhes";
}

<h1>Detalhes do Fornecedor</h1>

<div>
    <h4>Fornecedor</h4>
    <hr />
    <dl class="row">


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.RazaoSocial) *@
            Razao Social
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RazaoSocial)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.NomeFantasia) *@
            Nome Fantasia
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomeFantasia)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.NomeFantasia) *@
            CNPJ
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CNPJ)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Email) *@
            Email
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Telefone) *@
            Telefone
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.NomePessoaContato) *@
            Nome
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NomePessoaContato)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.CEP) *@
            CEP
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CEP)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.logradouro) *@
            logradouro
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.logradouro)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Complemento) *@
            Complemento
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Complemento)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Numero) *@
            Numero
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Numero)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Bairro) *@
            Bairro
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Bairro)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Municipio) *@
            Municipio
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Municipio)
        </dd>


        <dt class="col-sm-2">
            @* @Html.DisplayTelefoneFor(model => model.Municipio) *@
            Estado
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>




    </dl>
</div>
<div>
    <a class="btn btn-outline-primary btn-sm" asp-action="Edit" asp-route-id="@Model?.Id">Editar</a>
    <a class="btn btn-secondary text-white btn-sm" asp-action="Index">Voltar</a>
</div>

CadastroDeFornecedores/Views/Fornecedor/Edit.cshtml
@model CadastroDeFornecedores.Models.FornecedorModel

@{
    ViewData["Title"] = "Editar Informações do Fornecedor";
}

<h1>Adicionar Fornecedor</h1>

<h4>Fornecedor</h4>
<hr />
<div class="row">
    <div @* class="col-md-6" *@>
        <form class="row g-3" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-md-4">
                <label asp-for="CNPJ" class="form-label">CNPJ</label>
                <div class="input-group">
                    <!-- Adicione uma div com a classe "input-group" -->
                    <input asp-for="CNPJ" type="text" class="form-control" id="cleave-cnpj" />
                    <button class="btn btn-primary" id="search">Consultar CNPJ</button> <!-- Use a classe "btn" para estilizar o botão -->
                </div>
                <span asp-validation-for="CNPJ" class="text-danger"></span>
            </div>


            <div>
                <label asp-for="RazaoSocial" class="form-label">Razao Social</label>
                <input asp-for="RazaoSocial" class="form-control" id="razaoSocial" />
                <span asp-validation-for="RazaoSocial" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="NomeFantasia" class="form-label">Nome Fantasia</label>
                <input asp-for="NomeFantasia" class="form-control" id="nomeFantasia" />
                <span asp-validation-for="NomeFantasia" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="Email" class="form-label">Email</label>
                <input asp-for="Email" class="form-control" id="email" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="Telefone" class="form-label">Telefone</label>
                <input asp-for="Telefone" class="form-control" id="telefone" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="NomePessoaContato" class="form-label">Nome</label>
                <input asp-for="NomePessoaContato" class="form-control" />
                <span asp-validation-for="NomePessoaContato" class="text-danger"></span>
            </div>

            <div class="col-md-8">
                <label asp-for="CEP" class="form-label">CEP</label>
                <input asp-for="CEP" class="form-control" id="cep" />
                <span asp-validation-for="CEP" class="text-danger"></span>
            </div>


            <div class="col-md-6">
                <label asp-for="logradouro" class="form-label">logradouro</label>
                <input asp-for="logradouro" class="form-control" id="logradouro" />
                <span asp-validation-for="logradouro" class="text-danger"></span>
            </div>


            <div class="col-md-5">
                <label asp-for="Complemento" class="form-label">Complemento</label>
                <input asp-for="Complemento" class="form-control" id="complemento" />
                <span asp-validation-for="Complemento" class="text-danger"></span>
            </div>
            <div class="col-md-1">
                <label asp-for="Numero" class="form-label">Numero</label>
                <input asp-for="Numero" class="form-control" id="numero" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="col-md-6">
                <label asp-for="Bairro" class="form-label">Bairro</label>
                <input asp-for="Bairro" class="form-control" id="bairro" />
                <span asp-validation-for="Bairro" class="text-danger"></span>
            </div>
            <div class="col-md-4">
                <label asp-for="Municipio" class="form-label">Municipio</label>
                <input asp-for="Municipio" class="form-control" id="municipio" />
                <span asp-validation-for="Municipio" class="text-danger"></span>
            </div>



            <div class="form-group" style="padding-top:10px">
                <input type="submit" value="Inserir" class="btn btn-primary btn-sm" />
                <a class="btn btn-secondary text-white btn-sm" asp-action="Index">Voltar</a>
            </div>
        </form>
    </div>
</div>

CadastroDeFornecedores/Views/Fornecedor/Index.cshtml
@model IEnumerable<CadastroDeFornecedores.Models.FornecedorModel>
@{
    ViewData["Title"] = "Lista de Fornecedores";
}

<h1>Fornecedores</h1>



<p>
    <a class="btn btn-success" asp-action="Create">Adicionar Fornecedor</a>
</p>
<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Razão Social
            </th>


            <th>
                Nome Fantasia
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            </th>
            <th>
@*                 @Html.DisplayNameFor(model => model.NomePessoaContato) *@
                Nome
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr onclick="location.href='@Url.ActionLink("Details", "Fornecedor", new { Id = item.Id })'">

                <td>
                    @item.RazaoSocial
                </td>
                <td>
                    @item.NomeFantasia
                </td>
                <td>
                    @item.Email
                </td>
                <td>
                    @item.Telefone
                </td>
                <td>
                    @item.NomePessoaContato
                </td>

                <td>
                    <a class="btn btn-outline-primary btn-sm" asp-action="Edit" asp-route-id="@item.Id">Editar</a>
                    <a class="btn btn-outline-info btn-sm" asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
                    <a class="btn btn-danger btn-sm" asp-action="Delete" asp-route-id="@item.Id">Apagar</a>

                </td>
            </tr>
        }
    </tbody>
</table>

CadastroDeFornecedores/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadastroDeFornecedores</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CadastroDeFornecedores.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Fornecedor" asp-action="Index">Cadastro De Fornecedores 1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Cadastro De Fornecedores 2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Cadastro De Fornecedores 3</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cadastro De Fornecedores - <a asp-area="" asp-controller="Fornecedor" asp-action="Index">Inicio</a>
        </div>
    </footer>



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    

    
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            document.getElementById('search').addEventListener('click', function (e) {
                e.preventDefault();
                var cnpj = document.getElementById('cleave-cnpj').value.replace(/\D/g, '');

                var xhr = new XMLHttpRequest();
                xhr.open('GET', 'https://api-publica.speedio.com.br/buscarcnpj?cnpj=' + cnpj, true);
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === 4) {
                        if (xhr.status === 200) {
                            var data = JSON.parse(xhr.responseText);
                            // Preenche os campos de entrada com os valores obtidos da API
                            document.getElementById('razaoSocial').value = data['RAZAO SOCIAL']; 
                            document.getElementById('nomeFantasia').value = data['NOME FANTASIA'];
                            document.getElementById('email').value = data['EMAIL'];
                            // document.getElementById('telefone').value = data['TELEFONE'];
                            document.getElementById('cep').value = data['CEP'];
                            document.getElementById('numero').value = data['NUMERO'];
                            // document.getElementById('complemento').value = data['COMPLEMENTO'];
                            document.getElementById('bairro').value = data['BAIRRO'];
                            document.getElementById('municipio').value = data['MUNICIPIO'];
                            document.getElementById('uf').value = data['UF'];
                            // document.getElementById('logradouro').value = data['LOGRADOURO'];
                            // console.log(data['logradouro']);
                            // Preencha os outros campos de entrada conforme necessário
                        } else {
                            alert('Erro ao buscar informações do CNPJ.');
                        }
                    }
                };
                xhr.send();
            });
        });
    </script>



    <script>
        document.addEventListener('DOMContentLoaded', function () {
            document.getElementById('search').addEventListener('click', function (e) {
                e.preventDefault();
                var cnpj = document.getElementById('cleave-cnpj').value.replace(/\D/g, '');

                var xhr = new XMLHttpRequest();
                xhr.open('GET', 'https://minhareceita.org/' + cnpj, true);
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === 4) {
                        if (xhr.status === 200) {
                            var data = JSON.parse(xhr.responseText);
                            // Preenche os campos de entrada com os valores obtidos da API

                            // document.getElementById('razaoSocial').value = data['razao_social'];
                            // document.getElementById('nomeFantasia').value = data['nome_fantasia'];
                            // document.getElementById('email').value = data['email'];
                            document.getElementById('telefone').value = data['ddd_telefone_1'];
                            // document.getElementById('cep').value = data['cep'];
                            // document.getElementById('numero').value = data['numero'];
                            document.getElementById('complemento').value = data['complemento'];
                            document.getElementById('Estado').value = data['uf'];
                            // document.getElementById('bairro').value = data['bairro'];
                            // document.getElementById('municipio').value = data['municipio'];
                            // document.getElementById('uf').value = data['uf'];
                            // document.getElementById('nome_socio').value = data['nome_socio'];
                            // document.getElementById('logradouro').value = data['logradouro'];

                            //  OBSERVAÇÃO QUE ESSA LINHA GRANDE JUNTA 2 ITEM EM 1 INPUT
                            document.getElementById('logradouro').value = (data['descricao_tipo_de_logradouro'] || '') + ' ' + (data['logradouro'] || '');

                            console.log(data['logradouro']);



                            // Preencha os outros campos de entrada conforme necessário
                        } else {
                            alert('Erro ao buscar informações do CNPJ.');
                        }
                    }
                };
                xhr.send();
            });
        });
    </script>




    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.6/jquery.inputmask.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#telefone').inputmask('(99) 9999-9999', { placeholder: '_', showMaskOnHover: false, });
            $('#cleave-cnpj').inputmask('99.999.999/9999-99', { placeholder: '_', showMaskOnHover: false, });
            $('#cep').inputmask('99999-999', { placeholder: '_', showMaskOnHover: false, });
            $('#uf').inputmask('AA', { placeholder: '_', showMaskOnHover: false, });
            $('#numero').inputmask('999999', { placeholder: '', showMaskOnHover: false, });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>